steps:
  - command: "mvn clean"
    label: "maven"

  - block: "start deploy"

  - command: "echo deployed!"
    label: "deploy"

  - command: "echo test :rocket:"
    label: "deploy2"

  - command: "echo -e test2 :rocket:"
    label: "deploy3"

  - command: "testing.bat"
    label: "deploy4"
